version: "3.9"
services:
  #myserver:
  #build: .
  #ports:
  #  - "3000:3000"
  #links:
  #  - postgy
  #volumes:
  #  - .:/home/app
  # - /home/app
  postgy:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: ricardo
      POSTGRES_DB: perntodo
    volumes:
      - /var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ruperto1@protonmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    links:
      - postgy
volumes:
  postgres-data:
